### PR TITLE
Rename test scripts to test.py

### PR DESCRIPTION
**Pull request by dirkraft**
due to a change in https://github.com/allenai/s2-folks/pull/94#issuecomment-1554836690 to simplify/assume any example test scripts are also python

### CODE REVIEW

**Comment by dirkraft** [comment]
if you look at https://github.com/allenai/s2-folks/actions/runs/5074580424/jobs/9114905721#step:4:12 and cmd+f for `> Running` you will find three example test scripts that got run

**Comment by yoganandc** [comment]
why remove the shebang i dont get it

**Comment by dirkraft** [comment]
these are run explicitly with python now: https://github.com/allenai/s2-folks/blob/main/examples/python/run_tests.sh#L19

guess it doesn't matter, but would rather have consistency than imply we are detecting how to run these test scripts. we are not.

**Review by yoganandc — APPROVED** [review]
oki

**Pull request merged**
